//
//  ComputerVision.swift
//  MemoryEye
//
//  Created by Elizabeth Y Zou on 9/15/19.
//  Copyright © 2019 Peter T Tran. All rights reserved.
//

import UIKit
import Foundation

class ComputerVision {
    
    static var httpResponse: [String: Any] = [:]
    static var group: DispatchGroup = DispatchGroup()
    
    static func test() {
        print("Hello World")
        //        print(createTag(tag: "chicken"))
//        print(createImage(imageUrl: "https://www.animalsaustralia.org/images/features/1000-chickenlove-06-gab.jpg", tagID: "0027fc8e-1a84-4b39-8ce5-077922b8e8ee"))
    }
    
    /// Creates an tag Custom Vision.
    ///
    /// - Parameters:
    ///   - tagName: The name of the tag.
    /// - Returns: The tag ID generated by Custom Vision.
    static func createTag(tagName: String) -> String {
        requestWrapper(method: "POST", apiUrl: "tags?name=" + tagName, json: [:])
        return httpResponse["id"] as! String
    }
    
    /// Creates an image in Custom Vision associated with a given tag.
    ///
    /// - Parameters:
    ///   - imageUrl: The URL of the image.
    ///   - tagID: The tag ID generated by Custom Vision.
    static func createImage(imageUrl: String, tagID: String) {
        // create image
        let createImageJSON: [String: Any] = [
            "images": [
                [
                    "url": imageUrl
                ]
            ]
        ]
        requestWrapper(method: "POST", apiUrl: "images/urls", json: createImageJSON)
        
        // associate image with tag
        let imgs: Array<[String: Any]> = httpResponse["images"] as! Array
        let img = imgs[0]["image"] as! [String: Any]
        let imgID = img["id"] as! String
        associateImageAndTag(imageID: imgID, tagID: tagID)
    }
    
    /// Associates an image with a tag.
    ///
    /// - Parameters:
    ///   - imageID: The image ID generated by Custom Vision.
    ///   - tagID: The tag ID generated by Custom Vision.
    static func associateImageAndTag(imageID: String, tagID: String) {
        let associateJSON: [String: Any] = [
            "tags": [
                [
                    "imageId": imageID,
                    "tagId": tagID
                ]
            ]
        ]
        requestWrapper(method: "POST", apiUrl: "images/tags", json: associateJSON)
    }
    
    /// Sends HTTP requests until they succeed.
    ///
    /// - Parameters:
    ///   - method: The HTTP method of the request.
    ///   - apiUrl: The end of the request URL.
    ///   - json: A dictionary for the request body.
    static func requestWrapper(method: String, apiUrl: String, json: [String: Any]) {
        httpResponse = [:]
        while httpResponse.count == 0 || httpResponse["error"] != nil {
            group.enter()
            sendRequest(method: method, apiUrl: apiUrl, json: json)
            group.wait()
        }
    }
    
    /// Sends an HTTP request.
    ///
    /// - Parameters:
    ///   - method: The HTTP method of the request.
    ///   - apiUrl: The end of the request URL.
    ///   - json: A dictionary for the request body.
    static func sendRequest(method: String, apiUrl: String, json: [String: Any]) {
        // create request
        let httpUrl = "https://eastus.api.cognitive.microsoft.com/customvision/v3.0/training/projects/f248636d-d065-48fc-81ee-f7b43dbe613d/" + apiUrl
        guard let url = URL(string: httpUrl) else {
            return
        }
        var request = URLRequest(url: url)
        request.httpMethod = method
        
        // set header values
        let headers: [String: String] = ["Training-Key": "",
                                         "Content-Type": "application/json",
                                         "Training-key": "4b0f271e887740d2aa11154f42ee60b0"];
        for (key, value) in headers {
            request.setValue(value, forHTTPHeaderField: key)
        }
        
        // set body values
        let jsonData = try? JSONSerialization.data(withJSONObject: json)
        request.httpBody = jsonData
        
        // make the request
        let task = URLSession.shared.dataTask(with: request) { (data, response, error) in
            print("yay")
            guard let data = data, error == nil else {
                print(error?.localizedDescription ?? "No data")
                return
            }
            let responseJSON = try? JSONSerialization.jsonObject(with: data, options: [])
            if let responseJSON = responseJSON as? [String: Any] {
                httpResponse = responseJSON
                group.leave()
                print(responseJSON)
            }
        }
        task.resume()
    }
}
